min_version = "2026.4.18"

[settings]
experimental = true

[tools]
bun = "1.4.2"
hk = "1.58.1"

[task_config]
dir = "{{ config_root }}"

[env]
'_'.path = [
	"{{ config_root }}/node_modules/.bin",
	"{{ env.HOME }}/.local/bin",
]
HK_PKL_BACKEND = "pklr"
HK_MISE = 1

[deps.bun]
auto = true
sources = ["bun.lock", "bunfig.toml", "package.json", "docs/package.json", "packages/*/package.json"]
outputs = ["node_modules/.bun"]
run = "bun install"

[shell_alias]
mr = "mise run"
