[tasks."prepare:git-hooks"]
description = "Install hk Git hooks"
run = "hk install --mise"
sources = [".config/hk.pkl"]

[tasks.prepare]
description = "Prepare the monorepo"
run = [
	"mise run --no-deps prepare:git-hooks",
]
